name: bank_project
description: >-
  A small project to test my knowledge of Dart and Flutter. And also
  learn more about the language and the framework.
version: 1.0.0

repository: https://github.com/vellone-fabricio/flutter-studies

environment:
  sdk: '^3.3.0'
  
dev_dependencies:
  test: ^1.25.7
  coverage: ^1.8.0